In [1]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

/kaggle/input/mock-competition-2-ai-funaab/VariableDescription.csv
/kaggle/input/mock-competition-2-ai-funaab/train.csv
/kaggle/input/mock-competition-2-ai-funaab/test.csv
/kaggle/input/mock-competition-2-ai-funaab/sample_submission.csv

In [2]:
train =pd.read_csv('/kaggle/input/mock-competition-2-ai-funaab/train.csv',parse_dates=['YearOfObservation'],)
train.set_index('Customer Id', inplace=True)
train.head()

,YearOfObservation,Insured_Period,Residential,Building_Painted,Building_Fenced,Garden,Settlement,Building Dimension,Building_Type,Date_of_Occupancy,NumberOfWindows,Geo_Code,Claim
Customer Id,,,,,,,,,,,,,
H3793,2013-01-01,1.000000,0,V,N,O,R,900.0,1,1981.0,3,15014,1
H18227,2012-01-01,0.915301,0,V,N,O,R,1672.0,1,1983.0,4,36044,1
H13985,2016-01-01,1.000000,0,N,V,V,U,420.0,2,1988.0,.,13001,0
H17669,2013-01-01,1.000000,0,V,N,O,R,1956.0,2,1960.0,4,83009,1
H4156,2012-01-01,1.000000,0,V,V,V,U,800.0,1,1960.0,.,91174,0

In [3]:
test =pd.read_csv('/kaggle/input/mock-competition-2-ai-funaab/test.csv',parse_dates=['YearOfObservation'],)

test.set_index('Customer Id', inplace=True)
test.head()

,YearOfObservation,Insured_Period,Residential,Building_Painted,Building_Fenced,Garden,Settlement,Building Dimension,Building_Type,Date_of_Occupancy,NumberOfWindows,Geo_Code
Customer Id,,,,,,,,,,,,
H18966,2012-01-01,0.259563,0,V,N,O,R,1425.0,2,1950.0,7,13205
H16694,2016-01-01,0.997268,0,V,N,O,R,1264.0,3,1980.0,5,93048
H18661,2013-01-01,1.000000,0,V,N,O,R,2600.0,2,1962.0,4,30133
H18872,2013-01-01,1.000000,1,V,N,O,R,1015.0,3,1920.0,5,92012
H18032,2014-01-01,1.000000,1,V,N,O,R,15620.0,3,1978.0,>=10,59350

In [4]:
sample =pd.read_csv('/kaggle/input/mock-competition-2-ai-funaab/sample_submission.csv')
sample.head(2)

  Customer Id  Claim
0      H18966      1
1      H16694      0

In [5]:
train['source']='train'
test['source']='test'
data = pd.concat([train,test],ignore_index=False, sort=False)
data.head()

,YearOfObservation,Insured_Period,Residential,Building_Painted,Building_Fenced,Garden,Settlement,Building Dimension,Building_Type,Date_of_Occupancy,NumberOfWindows,Geo_Code,Claim,source
Customer Id,,,,,,,,,,,,,,
H3793,2013-01-01,1.000000,0,V,N,O,R,900.0,1,1981.0,3,15014,1.0,train
H18227,2012-01-01,0.915301,0,V,N,O,R,1672.0,1,1983.0,4,36044,1.0,train
H13985,2016-01-01,1.000000,0,N,V,V,U,420.0,2,1988.0,.,13001,0.0,train
H17669,2013-01-01,1.000000,0,V,N,O,R,1956.0,2,1960.0,4,83009,1.0,train
H4156,2012-01-01,1.000000,0,V,V,V,U,800.0,1,1960.0,.,91174,0.0,train

In [6]:
data.isnull().sum()* 100/ len(data)

YearOfObservation      0.000000
Insured_Period         0.000000
Residential            0.000000
Building_Painted       0.000000
Building_Fenced        0.000000
Garden                 0.097765
Settlement             0.000000
Building Dimension     1.480447
Building_Type          0.000000
Date_of_Occupancy      7.094972
NumberOfWindows        0.000000
Geo_Code               1.424581
Claim                 30.000000
source                 0.000000
dtype: float64

In [7]:
data.Garden.fillna('O',inplace=True)
data.Geo_Code.fillna('6088',inplace=True)
data['Building Dimension'].fillna(-999,inplace=True)

In [8]:
data.isnull().sum()* 100/ len(data)

YearOfObservation      0.000000
Insured_Period         0.000000
Residential            0.000000
Building_Painted       0.000000
Building_Fenced        0.000000
Garden                 0.000000
Settlement             0.000000
Building Dimension     0.000000
Building_Type          0.000000
Date_of_Occupancy      7.094972
NumberOfWindows        0.000000
Geo_Code               0.000000
Claim                 30.000000
source                 0.000000
dtype: float64

In [9]:
data.Date_of_Occupancy.fillna(-999,inplace=True)

In [10]:
data.info()

<class 'pandas.core.frame.DataFrame'>
Index: 7160 entries, H3793 to H3759
Data columns (total 14 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   YearOfObservation   7160 non-null   datetime64[ns]
 1   Insured_Period      7160 non-null   float64
 2   Residential         7160 non-null   int64
 3   Building_Painted    7160 non-null   object
 4   Building_Fenced     7160 non-null   object
 5   Garden              7160 non-null   object
 6   Settlement          7160 non-null   object
 7   Building Dimension  7160 non-null   float64
 8   Building_Type       7160 non-null   int64
 9   Date_of_Occupancy   7160 non-null   float64
 10  NumberOfWindows     7160 non-null   object
 11  Geo_Code            7160 non-null   object
 12  Claim               5012 non-null   float64
 13  source              7160 non-null   object
dtypes: datetime64[ns](1), float64(4), int64(2), object(7)
memory usage: 839.1+ KB

In [11]:
from sklearn import preprocessing
le = preprocessing.LabelEncoder()
data['Building_Painted']= le.fit_transform(data['Building_Painted'])
data['Building_Fenced']=le.fit_transform(data['Building_Fenced'])
data['Garden']=le.fit_transform(data['Garden'])
data['Settlement']=le.fit_transform(data['Settlement'])
data['NumberOfWindows']=le.fit_transform(data['NumberOfWindows'])

In [12]:

data.Date_of_Occupancy = data.Date_of_Occupancy.astype(int)
data.info()

<class 'pandas.core.frame.DataFrame'>
Index: 7160 entries, H3793 to H3759
Data columns (total 14 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   YearOfObservation   7160 non-null   datetime64[ns]
 1   Insured_Period      7160 non-null   float64
 2   Residential         7160 non-null   int64
 3   Building_Painted    7160 non-null   int64
 4   Building_Fenced     7160 non-null   int64
 5   Garden              7160 non-null   int64
 6   Settlement          7160 non-null   int64
 7   Building Dimension  7160 non-null   float64
 8   Building_Type       7160 non-null   int64
 9   Date_of_Occupancy   7160 non-null   int64
 10  NumberOfWindows     7160 non-null   int64
 11  Geo_Code            7160 non-null   object
 12  Claim               5012 non-null   float64
 13  source              7160 non-null   object
dtypes: datetime64[ns](1), float64(3), int64(8), object(2)
memory usage: 839.1+ KB

In [13]:
train= data.loc[data['source']=='train']
test=data.loc[data['source']=='test']

label= train.Claim
train_new=train.drop(['Garden','Claim','Geo_Code'], axis=1, inplace=True)
test_new=test.drop(['Garden','Geo_Code'],axis=1,inplace=True)

/opt/conda/lib/python3.7/site-packages/pandas/core/frame.py:4174: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  errors=errors,

In [14]:
y = label
X = train_new

test_df=test_new

In [15]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, stratify=y, test_size=0.3)

TypeError: Expected sequence or array-like, got <class 'NoneType'>

In [ ]:
from sklearn.linear_model import LogisticRegression
lr = LogisticRegression(C = 1,max_iter = 3000,class_weight = 'balanced',random_state=123)
lr.fit(X_train,y_train)
y_pred = lr.predict(X_test)
confusion_matrix(y_test,y_pred)